### ISSUE TITLE
10. How Sum?

### ISSUE THREAD

**Issue by lauracvilla-zz** [kurniawanlucky/odoo_addons#1]
I just install it and I can see my parents account and the information of the children. But please let me know how can I show on a parent account the value total of the sum of children account. Thanks for your help

**Comment by kurniawanlucky** [comment]
hallo @lauracvilla ,
you can follow this code:
```
from odoo import api, fields, models, _
class AccountAccount(models.Model):
    _inherit = 'account.account'

    count_child = fields.Integer('Child', compute='_compute_count_child')

    def _compute_count_child(self):
        for account in self.filtered(lambda r: r.child_ids):
            account.count_child = len(account.child_ids)
```
and don`t forget **inherit view account.account for show field count_child**

**Comment by lauracvilla-zz** [comment]
Thanks for your answer!

**Comment by kurniawanlucky** [comment]
your welcome
